Project unsplash_dataset {
  database_type: 'PostgreSQL'

  Note: '''
  You can merge the different datasets through the primary key ID fields
  (usually the `photo_id` field). With this you'll be able to cross-reference
  properties from the photos dataset with data from the keywords or conversions
  dataset.

  '''
}


Table photos {

  Note: '''
  The photos dataset has one row per photo. It contains properties of the photo,
  the name of the contributor, the image URL, and overall stats.
  '''
  

  photo_id                        text      [unique, pk, not null, note: 'ID of the Unsplash photo']
  photo_url                       text      [unique, not null, note: 'Permalink URL to the photo page on unsplash.com']
  photo_image_url                 text      [not null, note: 'URL of the image file. This is a the dynamic URL so you can apply resizing and customization operations directly on the image']
  photo_submitted_at              timestamp [not null, note: 'Timestamp of when the photo was submitted to Unsplash']
  photo_featured                  boolean   [not null, note: 'Whether the photo was promoted to the Editorial feed or not']
  photographer_username           text      [ note: 'Username of the photographer on Unsplash']
  photographer_first_name         text      [ note: 'First name of the photographer']
  photographer_last_name          text      [ note: 'Last name of the photographer']
  exif_camera_make                text      [ note: 'Camera make (brand) extracted from the EXIF data']
  exif_camera_model               text      [ note: 'Camera model extracted from the EXIF data']
  exif_iso                        integer   [ note: 'ISO setting of the camera,           extracted from the EXIF data']
  exif_aperture_value             text      [ note: 'Aperture setting of the camera,      extracted from the EXIF data']
  exif_focal_length               text      [ note: 'Focal length setting of the camera,  extracted from the EXIF data']
  exif_exposure_time              text      [ note: 'Exposure time setting of the camera, extracted from the EXIF data']
  photo_location_name             text      [ note: 'Location of the photo']
  photo_location_latitude         float     [ note: 'Latitude of the photo']
  photo_location_longitude        float     [ note: 'Longitude of the photo']
  photo_location_country          text      [ note: 'Country where the photo was made']
  photo_location_city             text      [ note: 'City where the photo was made']
  stats_views                     integer   [ note: 'Total # of times that a photo has been viewed on the Unsplash platform']
  stats_downloads                 integer   [ note: 'Total # of times that a photo has been downloaded via the Unsplash platform']
  ai_description                  text      [ note: 'Textual description of the photo,    generated by a 3rd party AI']
  ai_primary_landmark_name        text      [ note: 'Landmark present in the photo,       generated by a 3rd party AI']
  ai_primary_landmark_latitude    float     [ note: 'Latitude of the landmark,            generated by a 3rd party AI']
  ai_primary_landmark_longitude   float     [ note: 'Longitude of the landmark,           generated by a 3rd party AI']
  ai_primary_landmark_confidence  text      [ note: 'Landmark confidence of the 3rd party AI']

  indexes {
    photo_id [pk]
    photo_submitted_at
    photographer_username
    [exif_camera_make, exif_camera_model]
    exif_iso
    exif_aperture_value
    exif_exposure_time
  }

  Note: '''
    The photos dataset has one row per photo. It contains properties of the photo,
    the name of the contributor, the image URL, and overall stats.
  '''
}

Table keywords {

  photo_id                text    [not null, ref: > photos.photo_id, note: 'ID of the Unsplash photo']
  keyword                 text    [ not null, note: 'Keyword or search term' ]
  ai_service_1_confidence float   [ note: 'Confidence for the keyword from a 3rd party AI' ]
  ai_service_2_confidence float   [ note: 'Confidence for the keyword from another 3rd party AI' ]
  suggested_by_user       boolean [ not null, note: 'Whether the keyword was added by a user (a human)' ]

  indexes {
    (photo_id, keyword) [pk]
    keyword
  }

  Note: '''
    The `keywords.tsv` dataset has one row per photo-keyword pair. It contains
    data about how a keyword is connected to a photo and the conversions of the
    photo our search engine for a particular keyword.
  '''

}

Table collections {

  photo_id           text      [ not null, ref: > photos.photo_id, note: 'ID of the Unsplash photo' ]
  collection_id      text      [ not null, note: 'ID of the Unsplash collection containing the photo']
  collection_title   text      [ not null, note: 'Title of the collection containing the photo']
  photo_collected_at timestamp [ not null, note: 'Timestamp of when the photo was added to the collection' ]

  indexes {
    (photo_id, collection_id) [pk]
    collection_id
    collection_title
    photo_collected_at
  }

  Note: '''
    A collection on Unsplash is a user created grouping of photos. These are
    similar to boards on Pinterest and can often group photos in complex and
    creative ways.


    This table has has one row per photo-collection pair. Whenever a photo
    belongs to a collection created by a user, it will appear as one row. Each row describes
    when the photo was added to the collection and gives the title of the collection.
  '''

}

Table conversions {

  Note: '''
    A conversion is currently defined as a user selecting an image to download it.

    The conversions table has one row per search conversion. The dataset tells
    you which photo has been downloaded for a search, the country of origin, and
    an anonymous identifier to indiciate the unique users.
  '''

  conversion_type    text [not null, note: 'Type of conversion ("download" only for now)']
  keyword            text [not null, note: 'Keyword that was searched and led to the conversion']
  photo_id           text [not null, note: 'Photo ID of the photo that converted']
  anonymous_user_id  text [not null, note: 'Anonymous user ID']
  conversion_country text [not null, note: '2 letter ISO Country code of the device geolocation']

  indexes {
    keyword
    photo_id
    anonymous_user_id
    conversion_country
  }
}
